version: "3.3"
services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "db:/var/lib/postgresql/data"
    restart: unless-stopped

  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: unless-stopped

  server:
    image: ynput/ayon:latest
    restart: unless-stopped
    volumes:
      - "./addons:/addons"
      - "./storage:/storage"
      
      # comment out the following line on Windows
      - "/etc/localtime:/etc/localtime:ro"
      
      # uncomment the following line if you need to work on the backend code
      # - "./backend:/backend"
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    environment:
      - "AYON_POSTGRES_URL=postgres://ayon:ayon@postgres/ayon"
      - "AYON_DISCORD_CLIENT_ID=${AYON_DISCORD_CLIENT_ID-}"
      - "AYON_DISCORD_CLIENT_SECRET=${AYON_DISCORD_CLIENT_SECRET-}"
      - "AYON_GOOGLE_CLIENT_ID=${AYON_GOOGLE_CLIENT_ID-}"
      - "AYON_GOOGLE_CLIENT_SECRET=${AYON_GOOGLE_CLIENT_SECRET-}"
      - "AYON_MOTD_PATH=${AYON_MOTD_PATH-/storage/motd.md}"

volumes:
  db: {}
