version: "3.7"

services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "db:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayon"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: unless-stopped
    # TODO: This check floods logs (too many writes)
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  server:
    image: ynput/ayon:dev
    restart: unless-stopped
    volumes:
      - "./addons:/addons"
      - "./storage:/storage"
      
      # comment out the following line on Windows
      - "/etc/localtime:/etc/localtime:ro"
      
      # uncomment the following line if you need to work on the backend code
      # - "./backend:/backend"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis: {}
    environment:
      - "AYON_POSTGRES_URL=postgres://ayon:ayon@postgres/ayon"

volumes:
  db: {}

